CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code VARCHAR(255) NOT NULL UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    country_code VARCHAR(255) NOT NULL,
    use_case VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE phone_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(255) NOT NULL UNIQUE,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    region VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    released_at TIMESTAMP
);

CREATE INDEX idx_phone_numbers_client_id ON phone_numbers(client_id);
CREATE INDEX idx_phone_numbers_status ON phone_numbers(status);

CREATE TABLE call_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id VARCHAR(255) NOT NULL UNIQUE,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    from_number VARCHAR(255) NOT NULL,
    to_number VARCHAR(255) NOT NULL,
    direction VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    transcript TEXT,
    ai_response TEXT,
    escalation_requested BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    answered_at TIMESTAMP,
    ended_at TIMESTAMP
);

CREATE INDEX idx_call_sessions_client_created ON call_sessions(client_id, created_at DESC);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    event_summary VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    call_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_logs_client_created ON audit_logs(client_id, created_at DESC);